version: '3'
services:
  mysql:
    image: mysql:8.0          # Sử dụng MySQL phiên bản 8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Mật khẩu cho tài khoản root MySQL
      MYSQL_USER: user                # Tên người dùng MySQL
      MYSQL_PASSWORD: password        # Mật khẩu cho người dùng MySQL
      MYSQL_DATABASE: mydb            # Tên database sẽ được tạo cho ứng dụng
    ports:
      - "3306:3306"                  # Ánh xạ cổng 3306 của MySQL với cổng 3306 của máy host
    volumes:
      - mysql-data:/var/lib/mysql    # Gắn volume để lưu trữ dữ liệu MySQL

volumes:
  mysql-data:                        # Định nghĩa volume lưu trữ dữ liệu MySQL
