version: '3.7'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: userpassword
    depends_on:
      - mysql
    networks:
      - wp_network
    volumes:
      - wordpress_data:/var/www/html

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - wp_network

volumes:
  wordpress_data:
  mysql_data:

networks:
  wp_network:
    driver: bridge